### PR TITLE
Offset feature (skip_updates).

### PR DESCRIPTION
**Pull request by 9v2**
By the way, IDK if i wrote it correct, but this should add skip_updates feature in init of the client, which will skip all old updates, and get the new ones.

### CODE REVIEW

**Comment by 2ei** [comment]
You forgot to create new branch habibi, now 2 commits at one.

close this pr and open new one from new beanch.

**Comment by 9v2** [comment]
LOL, sorry.

**Comment by 2ei** [comment]
also you might have to use `ruff check tgram` and `ruff format` to pass all checks

**Review by 2ei — COMMENTED** [review]
Well now it's ready to merge, thanks.

**Pull request merged**
