### PR TITLE
Add keyboard chat request example

### PR DESCRIPTION
**Pull request by ihatemyself0**

### CODE REVIEW

**Comment by 2ei** [comment]
Thank you

**Comment by ihatemyself0** [comment]
https://github.com/2ei/tgram/assets/173957402/d589e866-ef69-4e11-9ca7-7f1933f49927

**Comment by 2ei** [comment]
> doc_2024-06-30_16-17-39.mp4

lol i didn't know that we can comment gif here..

**Comment by ihatemyself0** [comment]
here the best place to do everything you want /s

**Pull request merged**
