### PR TITLE
add chat types filter

### PR DESCRIPTION
**Pull request by ihatemyself0**

### CODE REVIEW

**Review by 2ei — COMMENTED** [review]
```python
group = chat_type_filter(["group", "supergroup"])
```
i think it's better to add filter for each type, not both at once.

**Comment by ihatemyself0** [comment]
> ```python
> group = chat_type_filter(["group", "supergroup"])
> ```
> 
> i think it's better to add filter for each type, not both at once.

both are group chats…

**Comment by 2ei** [comment]
i will test it - after testing it should be merged.

**Comment by 2ei** [comment]
Thanks you

**Pull request merged**
